using UnityEngine;
using TMPro;

public enum TutorialStep
{
    None,
    Move,
    OpenMap,
    End
}

public class TutorialManager : MonoBehaviour
{public static TutorialManager Instance;

    [Header("UI")]
    [SerializeField] private GameObject tutorialUI;
    [SerializeField] private TextMeshProUGUI tutorialText;

    private TutorialStep currentStep = TutorialStep.None;

    private void Awake()
    {
        Debug.Log("ğŸŸ¢ TutorialManager Awake");
       if (Instance == null)
           Instance = this;
        else
            Destroy(gameObject);
    }

   private void Update()
   {
        if (currentStep == TutorialStep.None) return;

        switch (currentStep)
        {
           case TutorialStep.Move:
                CheckMoveInput();
                break;

            case TutorialStep.OpenMap:
                CheckMapInput();
                break;
        } 
   }

    // NPC ëŒ€ì‚¬ ëë‚˜ë©´ ì—¬ê¸° í˜¸ì¶œ
    public void StartTutorial()
    {
        tutorialUI.SetActive(true);
        SetStep(TutorialStep.Move);
    }

    private void SetStep(TutorialStep step)
    {
        currentStep = step;

        switch (step)
        {
            case TutorialStep.Move:
                tutorialText.text = "W A S D ë˜ëŠ” ë°©í–¥í‚¤ë¡œ ì´ë™í•´ ë³´ì„¸ìš”";
                break;

            case TutorialStep.OpenMap:
                tutorialText.text = "M í‚¤ë¥¼ ëˆŒëŸ¬ ì§€ë„ë¥¼ ì—´ì–´ë³´ì„¸ìš”";
                break;

            case TutorialStep.End:
                EndTutorial();
                break;
        }
    }

    private void CheckMoveInput()
    {
        if (Input.GetAxisRaw("Horizontal") != 0 ||
            Input.GetAxisRaw("Vertical") != 0)
        {
            SetStep(TutorialStep.OpenMap);
        }
    }

    private void CheckMapInput()
    {
        if (Input.GetKeyDown(KeyCode.M))
        {
            SetStep(TutorialStep.End);
        }
    }

    private void EndTutorial()
    {
        tutorialUI.SetActive(false);
        currentStep = TutorialStep.None;
    }
}